name: twenty_four_online_interview_test
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^1.24.0
  cloud_firestore: ^3.5.0
  firebase_auth: ^3.11.0
  equatable: ^2.0.5
  auto_route: ^3.2.4
  flutter_bloc: ^8.0.1
  logger: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  auto_route_generator: ^3.2.3
  build_runner: ^2.1.8

flutter:
  uses-material-design: true